In [1]:
import numpy as np
from graspy.simulations import p_from_latent, sample_edges_corr


Bad key "text.kerning_factor" on line 4 in
C:\Users\dfran\Miniconda3\envs\ndd_4\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test_patch.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution


In [2]:
from platform import python_version
print(python_version())

3.8.5


In [3]:
np.random.seed(1234)
X = np.random.dirichlet([1, 1], size=5)
Y = None
from graspy.simulations.rdpg_corr import rdpg_corr

In [4]:
x = rdpg_corr(X, Y, 0.3, rescale=False, directed=False, loops=False)

In [5]:
x[0].shape

(5, 5)

So what is seen here is that this actually matches the output that is in the master file on line 73 but for some reason when running travis it is not correct 

In [6]:
x

(array([[0., 1., 0., 1., 0.],
        [1., 0., 0., 1., 1.],
        [0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.]]),
 array([[0., 1., 0., 1., 0.],
        [1., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.]]))

Instead what travis prefers to see is this. This is where the issue comes to is if travis or the new update. I am still confused I have thus shown (to the best of my knowledge that the code seems to be getting the desires outputs(compared to what the docstring tests says) when ran here but when ran in travis they rpoduce different results. I am unsure how that is possible.

In [ ]:
#output that travis build wants rdpg_corr.py
(array([[0., 1., 0., 1., 1.],
            [1., 0., 0., 1., 0.],
            [0., 0., 0., 0., 0.],
            [1., 1., 0., 0., 1.],
            [1., 0., 0., 1., 0.]]), array([[0., 1., 0., 1., 1.],
            [1., 0., 1., 1., 0.],
            [0., 1., 0., 0., 0.],
            [1., 1., 0., 0., 1.],
            [1., 0., 0., 1., 0.]]))

In [ ]:
Here I try and work with simulations.py and see where things go wrong and again this output in the notebook gets the output that the docstring in on line 704 in simulations.py wants. 

In [39]:
np.random.seed(1)

In [24]:
X = np.random.dirichlet([1, 1], size=5)

In [25]:
from graspy.simulations.simulations import rdpg
rdpg(X, loops=False)

array([[0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

yet again when run through travis it produces the following output and I am unsure why. 

In [ ]:
#output travis build wants for simulations.py 
array([[0., 1., 1., 1., 0.],
            [1., 0., 0., 1., 1.],
            [1., 0., 0., 1., 0.],
            [1., 1., 1., 0., 1.],
            [0., 1., 0., 1., 0.]])


In [41]:

#but this is random output of number and so it will be different each time, I assume that if follows the correct distribution
#mainly because we get the same output 
samples = np.random.binomial(1, .7)
print(samples)

0
